#name: Publish to PyPI
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-publish:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Check out code
#      uses: actions/checkout@v3
#
#    - name: Set up Python
#      uses: actions/setup-python@v3
#      with:
#        python-version: '3.x'
#
#    - name: Install Flit
#      run: python -m pip install flit
#
#    - name: Build and Publish to PyPI
#      env:
#        FLIT_USERNAME: '__token__'
#        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#      run: flit publish
#
